services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: japh-portfolio:latest
    container_name: japh-portfolio
    env_file:
      - path: .env.local
        required: false
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
